package com.sodepa.erp.utils;

public enum MakerCheckerEntityName {
    BANQUE, FISCALYEARCLOSING, TIERS, COMPTE, ECRITURE, IMMOBILISATION, JOURNAL, LIGNEECRITURE, LIGNERELEVEBANCAIRE, RELEVEBANCAIRE, USER
}
