package com.sodepa.erp.utils;

public enum Permissions {
    INIT_CREATE_BANK,
    INIT_UPDATE_BANK_INFO,
    GET_FULL_BANK_INFO,
    VALIDATE_OR_REJECT_BANK_INFO,
    INIT_CREATE_TIERS,
    INIT_UPDATE_TIERS,
    GET_FULL_TIERS_INFO,
    VALIDATE_OR_REJECT_TIERS,
    INIT_CREATE_COMPTE,
    INIT_UPDATE_COMPTE,
    GET_FULL_COMPTE_INFO,
    VALIDATE_OR_REJECT_COMPTE,
    INIT_CREATE_JOURNAL,
    INIT_UPDATE_JOURNAL,
    GET_FULL_JOURNAL_INFO,
    VALIDATE_OR_REJECT_JOURNAL,
    
    INIT_CREATE_IMMOBILISATION,
    INIT_UPDATE_IMMOBILISATION,
    GET_FULL_IMMOBILISATION_INFO,
    VALIDATE_OR_REJECT_IMMOBILISATION,
    INIT_CREATE_ECRITURE,
    GET_FULL_ECRITURE_INFO,
    VALIDATE_OR_REJECT_ECRITURE,
    INIT_CREATE_USER,
    INIT_UPDATE_USER,
    GET_FULL_USER_INFO,
    VALIDATE_OR_REJECT_USER,

    INIT_CREATE_FISCAL_YEAR_CLOSING,

}
