spring:
  devtools:
    restart:
      enabled: false
      poll-interval: 5000
      quiet-period: 4000
  application:
    name: erp
  cache:
    type: redis
  data:
    redis:
      port: 6379
      host: localhost
  datasource:
    url: jdbc:postgresql://localhost:5433/sodepa
    username: toto
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db-changelog-master.yaml
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8070/realms/sodepa
          jwk-set-uri: http://localhost:8070/realms/sodepa/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: sodepa
            client-secret: YrLn2AuVUNAtafaOtj8DDs4CFJrv4eMp
            scope: openid,profile,email
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8070/realms/sodepa
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-management-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8082

# Keycloak Admin
keycloak:
  default-password: "DefaultPassword123!"
  admin:
    server-url: http://localhost:8070
    realm: sodepa
    client-id: sodepa
    client-secret: YrLn2AuVUNAtafaOtj8DDs4CFJrv4eMp

# Minio
minio:
  endpoint: http://localhost:7004
  fileurl: http://localhost:7004
  access-key: minioadmin
  secret-key: minioadmin123
  bucket: avatars
  bucket-name: avatars
  region: us-east-1
  enabled: true

# Springdoc
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

collabora:
  url: http://localhost:9980
app:
  public_url: http://172.24.208.1:8087
  duration: 30

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
  datadog:
    metrics:
      export:
        enabled: false
  otlp:
    metrics:
      export:
        enabled: false

clickhouse:
  url: jdbc:ch://localhost:8123/default?compress=0&decompress=0
  url-http: http://localhost:8123
  username: default
  password: ""